spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/batch
    username: batchuser
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

logging:
  level:
    root: info
