spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/batch
    username: batchuser
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    root: info

server:
  port: 8080

